### PR TITLE
Convert env variables into hash to solve bug

### PR DESCRIPTION
**Pull request by gugaiz**
This solve a bug that happens when trying to merge env variables into a hash. It generates the error below if this bugfix is not applied

```
tfctl-1.2.1/lib/tfctl/executor.rb:54:in `run': undefined method `merge' for {}:Object (NoMethodError)
```

It also solved bug #14 and #12

### CODE REVIEW

**Comment by word** [comment]
Hi, thanks for the PR.

I think this may be a regression caused by PR #11.

`Open3.popen3` uses `Process.spawn` under the hood.  The spawned process should inherit the parent's processes environment unless explicitly cleared with `:unsetenv_others` which we don't do.  Therefore I don't think the changes in PR #11 were necessary so we can probably get it reverted and fix the issue.

More details in the `Process.spawn` docs: https://www.rubydoc.info/stdlib/core/Process.spawn

I will give it a test later today and get back to you.

**Comment by word** [comment]
Reverted #11 and this has fixed the problem.  I also released a new gem version 1.2.2 which contains the fix.

Many thanks for reporting the problem.
